spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: HiveRH
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

hiverh:
  bootstrap-admin:
    enabled: ${BOOTSTRAP_ADMIN_ENABLED:false}
    user: ${BOOTSTRAP_ADMIN_USER:admin}
    email: ${BOOTSTRAP_ADMIN_EMAIL:admin@hiverh.local}
    password: ${BOOTSTRAP_ADMIN_PASSWORD:}


